require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CallbacksController do

  # This should return the minimal set of attributes required to create a valid
  # Callback. As you add validations to Callback, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CallbacksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all callbacks as @callbacks" do
      callback = Callback.create! valid_attributes
      get :index, {}, valid_session
      assigns(:callbacks).should eq([callback])
    end
  end

  describe "GET show" do
    it "assigns the requested callback as @callback" do
      callback = Callback.create! valid_attributes
      get :show, {:id => callback.to_param}, valid_session
      assigns(:callback).should eq(callback)
    end
  end

  describe "GET new" do
    it "assigns a new callback as @callback" do
      get :new, {}, valid_session
      assigns(:callback).should be_a_new(Callback)
    end
  end

  describe "GET edit" do
    it "assigns the requested callback as @callback" do
      callback = Callback.create! valid_attributes
      get :edit, {:id => callback.to_param}, valid_session
      assigns(:callback).should eq(callback)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Callback" do
        expect {
          post :create, {:callback => valid_attributes}, valid_session
        }.to change(Callback, :count).by(1)
      end

      it "assigns a newly created callback as @callback" do
        post :create, {:callback => valid_attributes}, valid_session
        assigns(:callback).should be_a(Callback)
        assigns(:callback).should be_persisted
      end

      it "redirects to the created callback" do
        post :create, {:callback => valid_attributes}, valid_session
        response.should redirect_to(Callback.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved callback as @callback" do
        # Trigger the behavior that occurs when invalid params are submitted
        Callback.any_instance.stub(:save).and_return(false)
        post :create, {:callback => {  }}, valid_session
        assigns(:callback).should be_a_new(Callback)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Callback.any_instance.stub(:save).and_return(false)
        post :create, {:callback => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested callback" do
        callback = Callback.create! valid_attributes
        # Assuming there are no other callbacks in the database, this
        # specifies that the Callback created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Callback.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => callback.to_param, :callback => { "these" => "params" }}, valid_session
      end

      it "assigns the requested callback as @callback" do
        callback = Callback.create! valid_attributes
        put :update, {:id => callback.to_param, :callback => valid_attributes}, valid_session
        assigns(:callback).should eq(callback)
      end

      it "redirects to the callback" do
        callback = Callback.create! valid_attributes
        put :update, {:id => callback.to_param, :callback => valid_attributes}, valid_session
        response.should redirect_to(callback)
      end
    end

    describe "with invalid params" do
      it "assigns the callback as @callback" do
        callback = Callback.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Callback.any_instance.stub(:save).and_return(false)
        put :update, {:id => callback.to_param, :callback => {  }}, valid_session
        assigns(:callback).should eq(callback)
      end

      it "re-renders the 'edit' template" do
        callback = Callback.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Callback.any_instance.stub(:save).and_return(false)
        put :update, {:id => callback.to_param, :callback => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested callback" do
      callback = Callback.create! valid_attributes
      expect {
        delete :destroy, {:id => callback.to_param}, valid_session
      }.to change(Callback, :count).by(-1)
    end

    it "redirects to the callbacks list" do
      callback = Callback.create! valid_attributes
      delete :destroy, {:id => callback.to_param}, valid_session
      response.should redirect_to(callbacks_url)
    end
  end

end
